### PR TITLE
Add files

### PR DESCRIPTION
**Pull request by hazim1093**
Add dockerfile script and readme

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-5`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-6`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-8`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-9`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-10`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-11`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-12`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-13`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-14`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-15`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-16`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-17`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-18`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-19`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube-settings:SNAPSHOT-PR-1-20`

**Review by rasheedamir — APPROVED** [review]
well done

**Pull request merged**
